config/routes.rb
Rails.application.routes.draw do
  constraints ThemeRouteConstraint.new do
    scope "(*theme)" do
      get "/about", to: 'pages#about', as: :about
      get '/education', to: 'pages#education', as: :education
      get '/employment', to: 'pages#employment', as: :employment
      get '/interests', to: 'pages#interests', as: :interests
      get '/skills', to: 'pages#skills', as: :skills

      root to: 'pages#welcome'
    end
  end
end

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
  <header>
    <%= image_tag 'me.jpg', class: 'avatar' %>
  </header>

  <nav>
    <%= nav_link_to 'About', about_path %>
    <%= nav_link_to 'Employment', employment_path %>
    <%= nav_link_to 'Education', education_path %>
    <%= nav_link_to 'Skills', skills_path %>
    <%= nav_link_to 'Interests', interests_path %>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrentOdell.com</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'favicons/apple-icon-57x57.png' %>">
    <link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'favicons/apple-icon-60x60.png' %>">
    <link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'favicons/apple-icon-72x72.png' %>">
    <link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'favicons/apple-icon-76x76.png' %>">
    <link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'favicons/apple-icon-114x114.png' %>">
    <link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'favicons/apple-icon-120x120.png' %>">
    <link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'favicons/apple-icon-144x144.png' %>">
    <link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'favicons/apple-icon-152x152.png' %>">
    <link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'favicons/apple-icon-180x180.png' %>">
    <link rel="icon" type="image/png" sizes="192x192"  href="<%= image_path 'favicons/android-icon-192x192.png' %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'favicons/favicon-32x32.png' %>">
    <link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'favicons/favicon-96x96.png' %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'favicons/favicon-16x16.png' %>">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="<%= image_path 'favicons/ms-icon-144x144.png' %>">
    <meta name="theme-color" content="#ffffff">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class="<%= body_class %>">
    <div class="layout-wrapper">
      <%= render partial: 'layouts/sidebar' %>

      <main class="main-content">
        <%= yield %>
      </main>
    </div>
  </body>
</html>